export enum TravelServerStatusEnum {
  SEARCHING_DRIVER = "SEARCHING_DRIVER",
	WITH_DRIVER_ASSIGNED = "WITH_DRIVER_ASSIGNED",
	GOING_TO_CLIENT = "GOING_TO_CLIENT",
	GOING_TO_DESTINATION = "GOING_TO_DESTINATION",
	ARRIVE_TO_DESTINATION = "ARRIVE_TO_DESTINATION",
	WAITING_FOR_PAYMENT = "WAITING_FOR_PAYMENT", //only for passenger app
	CLOSING_TRAVEL = "CLOSING_TRAVEL",
	DONE = "DONE",
	CANCELLED = "CANCELLED",
	PROGRAMMED = "PROGRAMMED",
	LOST = "LOST",
}

/* Strings i18n */
export enum TravelStatusLabelEnum {
  SEARCHING_DRIVER = "travel_status.SEARCHING_DRIVER",
	WITH_DRIVER_ASSIGNED = "travel_status.WITH_DRIVER_ASSIGNED",
	SEARCHING_DRIVER_SCHEDULED = "travel_status.SEARCHING_DRIVER_SCHEDULED",
	WITH_DRIVER_ASSIGNED_SCHEDULED = "travel_status.WITH_DRIVER_ASSIGNED_SCHEDULED",
	GOING_TO_CLIENT = "travel_status.GOING_TO_CLIENT",
	GOING_TO_DESTINATION = "travel_status.GOING_TO_DESTINATION",
	ARRIVE_TO_DESTINATION = "travel_status.ARRIVE_TO_DESTINATION",
	WAITING_FOR_PAYMENT = "travel_status.WAITING_FOR_PAYMENT",
	CLOSING_TRAVEL = "travel_status.CLOSING_TRAVEL",
	DONE = "travel_status.DONE",
	CANCELLED = "travel_status.CANCELLED",
	PROGRAMMED = "travel_status.PROGRAMMED",
	LOST = "travel_status.LOST",
}
